[versions]

# Language
kotlin = "2.0.20"
ksp = "2.0.20-1.0.24"
asm = "9.7"
bytebuddy = "1.14.15"

# Platforms
proxy-velocity = "3.3.0-SNAPSHOT"
server-paper = "1.20.6-R0.1-SNAPSHOT"
server-purpur = "1.20.6-R0.1-SNAPSHOT"

# Libraries
adventure = "4.17.0"
arrow = "1.2.4"
cloud = "1.8.4"
cloud2 = "2.0.0"
cloud2-minecraft = "2.0.0-beta.11"
cloud2-processors = "1.0.0-rc.1"
configurate = "4.2.0-SNAPSHOT"
commons = "1.9"
creative = "1.9.1"
dokka = "1.9.20"
exposed = "1.0.0-beta-2"
hephaestus = "0.11.0-dev-SNAPSHOT"
packetevents = "2.7.0"
mocha = "3.0.0"
i18n = "1.3-SNAPSHOT"
invui = "1.43"
mccoroutine = "2.16.0"
shadow-nbt = "1.20.6-SNAPSHOT"

# Build
indra = "3.1.3"
shadow = "8.3.0"

# Test
mockk = "1.13.10"
mockbukkit = "3.93.2"
junit4 = "4.13.2"
junit5 = "5.10.2"
logback-classic = "1.5.6"

[libraries]

# BuildSrc plugins
indra-common = { group = "net.kyori", name = "indra-common", version.ref = "indra" }
indra-licenser-spotless = { group = "net.kyori", name = "indra-licenser-spotless", version.ref = "indra" }
indra-publishing-sonatype = { group = "net.kyori", name = "indra-publishing-sonatype", version.ref = "indra" }
shadow = { group = "com.gradleup.shadow", name = "com.gradleup.shadow.gradle.plugin", version.ref = "shadow" }
kotlin-jvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
kotlin-plugin-serialization = { group = "org.jetbrains.kotlin.plugin.serialization", name = "org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
kotlin-plugin-atomicfu = { group = "org.jetbrains.kotlin.plugin.atomicfu", name = "org.jetbrains.kotlin.plugin.atomicfu.gradle.plugin", version.ref = "kotlin" }
ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
dokka = { group = "org.jetbrains.dokka", name = "org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }

# BOMs
bom-adventure = "cc.mewcraft.bom:adventure:0.1"
bom-anvilgui = "cc.mewcraft.bom:anvil-gui:0.1"
bom-asm = "cc.mewcraft.bom:asm:0.1"
bom-caffeine = "cc.mewcraft.bom:caffeine:0.1"
bom-cloud-confirmation = "cc.mewcraft.bom:cloud-confirmation:0.1"
bom-cloud-kotlin = "cc.mewcraft.bom:cloud-kotlin:0.1"
bom-cloud-paper = "cc.mewcraft.bom:cloud-paper:0.3"
bom-cloud-velocity = "cc.mewcraft.bom:cloud-velocity:0.1"
bom-configurate-gson = "cc.mewcraft.bom:configurate-gson:0.1"
bom-configurate-yaml = "cc.mewcraft.bom:configurate-yaml:0.1"
bom-configurate-extra-kotlin = "cc.mewcraft.bom:configurate-extra-kotlin:0.2"
bom-configurate-extra-dfu4 = "cc.mewcraft.bom:configurate-extra-dfu4:0.2"
bom-configurate-extra-dfu8 = "cc.mewcraft.bom:configurate-extra-dfu8:0.1"
bom-creative = "cc.mewcraft.bom:creative:0.4"
bom-exposed = "cc.mewcraft.bom:exposed:0.2"
bom-hephaestus = "cc.mewcraft.bom:hephaestus:0.1"
bom-invui = "cc.mewcraft.bom:invui:0.2"
bom-jgit = "cc.mewcraft.bom:jgit:0.1"
bom-packetevents-spigot = "cc.mewcraft.bom:packetevents-spigot:0.2"

# Proxy server platforms
proxy-velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "proxy-velocity" }

# Game server platforms
server-paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "server-paper" }
server-purpur = { group = "org.purpurmc.purpur", name = "purpur-api", version.ref = "server-purpur" }

# Generic
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version = "3.1.8" }
commons-io = { group = "commons-io", name = "commons-io", version = "2.16.1" }
guava = { group = "com.google.guava", name = "guava", version = "33.5.0-jre" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
arrow-optics-ksp-plugin = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }
jgit = { group = "org.eclipse.jgit", name = "org.eclipse.jgit", version = "6.9.0.202403050737-r" }
commons-collections = { group = "cc.mewcraft.commons", name = "commons-collections", version.ref = "commons" }
commons-gson = { group = "cc.mewcraft.commons", name = "commons-gson", version.ref = "commons" }
commons-provider = { group = "cc.mewcraft.commons", name = "commons-provider", version.ref = "commons" }
commons-reflection = { group = "cc.mewcraft.commons", name = "commons-reflection", version.ref = "commons" }
commons-tuple = { group = "cc.mewcraft.commons", name = "commons-tuple", version.ref = "commons" }

# Java bytecode manipulation
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asm-commons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm" }
bytebuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "bytebuddy" }
bytebuddy-agent = { group = "net.bytebuddy", name = "byte-buddy-agent", version.ref = "bytebuddy" }

# Testing environment
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit5-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockbukkit = { group = "com.github.seeseemelk", name = "MockBukkit-v1.20", version.ref = "mockbukkit" }

# Compile-time checking
checker-jetbrains = { group = "org.jetbrains", name = "annotations", version = "24.1.0" }
checker-qual = { group = "org.checkerframework", name = "checker-qual", version = "3.42.0" }

# MC Coroutine (Do not use it. Use the bundle instead)
mccoroutine-bukkit-api = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-api", version.ref = "mccoroutine" }
mccoroutine-bukkit-core = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-core", version.ref = "mccoroutine" }
mccoroutine-velocity-api = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-velocity-api", version.ref = "mccoroutine" }
mccoroutine-velocity-core = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-velocity-core", version.ref = "mccoroutine" }

# Spatula Item API
spatula-item = { group = "cc.mewcraft.spatula.item", name = "api", version = "1.0.0" }

# TownyLink API
townylink = { group = "cc.mewcraft.townylink", name = "api", version = "1.0.0" }

# Dependency injection
guice = { group = "com.google.inject", name = "guice", version = "5.1.0" }
guice-assistedinject = { group = "com.google.inject.extensions", name = "guice-assistedinject", version = "5.1.0" }
koin-core = { group = "io.insert-koin", name = "koin-core", version = "3.5.6" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version = "1.3.1" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version = "1.3.1" }

# SQL
hikari = { group = "com.zaxxer", name = "HikariCP", version = "5.1.0" }

# Redis
jedis = { group = "redis.clients", name = "jedis", version = "4.4.8" }

# Adventure
adventure-nbt = { group = "net.kyori", name = "adventure-nbt", version.ref = "adventure" }
adventure-extra-kotlin = { group = "net.kyori", name = "adventure-extra-kotlin", version.ref = "adventure" }
adventure-text-serializer-ansi = { group = "net.kyori", name = "adventure-text-serializer-ansi", version.ref = "adventure" }

# Commands
cloud-paper = { group = "cloud.commandframework", name = "cloud-paper", version.ref = "cloud" }
cloud-velocity = { group = "cloud.commandframework", name = "cloud-velocity", version.ref = "cloud" }
cloud-minecraft-extras = { group = "cloud.commandframework", name = "cloud-minecraft-extras", version.ref = "cloud" }
cloud-kotlin-extensions = { group = "cloud.commandframework", name = "cloud-kotlin-extensions", version.ref = "cloud" }
cloud-kotlin-coroutines = { group = "cloud.commandframework", name = "cloud-kotlin-coroutines", version.ref = "cloud" }

cloud2-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud2" }
cloud2-kotlin-extensions = { group = "org.incendo", name = "cloud-kotlin-extensions", version.ref = "cloud2" }
cloud2-kotlin-coroutines = { group = "org.incendo", name = "cloud-kotlin-coroutines", version.ref = "cloud2" }
cloud2-paper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloud2-minecraft" }
cloud2-velocity = { group = "org.incendo", name = "cloud-velocity", version.ref = "cloud2-minecraft" }
cloud2-minecraft-extras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "cloud2-minecraft" }
cloud2-processors-confirmation = { group = "org.incendo", name = "cloud-processors-confirmation", version.ref = "cloud2-processors" }

# Configuration
configurate-yaml = { group = "cc.mewcraft.configurate", name = "configurate-yaml", version.ref = "configurate" }
configurate-gson = { group = "cc.mewcraft.configurate", name = "configurate-gson", version.ref = "configurate" }
configurate-extra-kotlin = { group = "cc.mewcraft.configurate", name = "configurate-extra-kotlin", version.ref = "configurate" }
configurate-extra-dfu4 = { group = "cc.mewcraft.configurate", name = "configurate-extra-dfu4", version.ref = "configurate" }
configurate-extra-dfu8 = { group = "cc.mewcraft.configurate", name = "configurate-extra-dfu8", version.ref = "configurate" }
simplixstorage = { group = "com.github.simplix-softworks", name = "simplixstorage", version = "3.2.6" }

# I18n
lang-bukkit = { group = "de.themoep.utils", name = "lang-bukkit", version.ref = "i18n" }
lang-velocity = { group = "de.themoep.utils", name = "lang-velocity", version.ref = "i18n" }

# Resourcepacks
creative-api = { group = "team.unnamed", name = "creative-api", version.ref = "creative" }
creative-serializer-minecraft = { group = "team.unnamed", name = "creative-serializer-minecraft", version.ref = "creative" }
creative-server = { group = "team.unnamed", name = "creative-server", version.ref = "creative" }

# Model Engine (Ticxo)
modelengine-api = { group = "com.ticxo.modelengine", name = "ModelEngine", version = "R4.0.6" }

# Model Engine (hephaestus)
hephaestus-core = { group = "team.unnamed", name = "hephaestus-api", version.ref = "hephaestus" }
hephaestus-reader-blockbench = { group = "team.unnamed", name = "hephaestus-reader-blockbench", version.ref = "hephaestus" }
hephaestus-runtime-bukkit-api = { group = "team.unnamed", name = "hephaestus-runtime-bukkit-api", version.ref = "hephaestus" }
hephaestus-runtime-bukkit-adapt = { group = "team.unnamed", name = "hephaestus-runtime-bukkit-adapt-v1_20_R3", version.ref = "hephaestus" }

# NBT
shadow-nbt = { group = "cc.mewcraft", name = "shadow-nbt", version.ref = "shadow-nbt" }

# PacketEvents
packetevents-spigot = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }
packetevents-velocity = { group = "com.github.retrooper", name = "packetevents-velocity", version.ref = "packetevents" }

# Mocha
mocha = { group = "team.unnamed", name = "mocha", version.ref = "mocha" }

# Expression parser
evalex = { group = "com.ezylang", name = "EvalEx", version = "3.2.0" }

# Cron
cronutils = { group = "com.cronutils", name = "cron-utils", version = "9.2.1" }

# Exposed
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
exposed-javatime = { group = "org.jetbrains.exposed", name = "exposed-java-time", version.ref = "exposed" }

# Fast GUI creation
anvilgui = { group = "net.wesjd", name = "anvilgui", version = "1.6.5-SNAPSHOT" }
invui-core = { group = "xyz.xenondevs.invui", name = "invui-core", version.ref = "invui" }
invui-invaccess = { group = "xyz.xenondevs.invui", name = "inventory-access", version.ref = "invui" }
invui-invaccess-nms = { group = "xyz.xenondevs.invui", name = "inventory-access-r21", version.ref = "invui" }
invui-extra-kotlin = { group = "xyz.xenondevs.invui", name = "invui-kotlin", version.ref = "invui" }

# Standalone Paper/Velocity plugins
mewcore = { group = "cc.mewcraft", name = "mewcore", version = "latest.release" }
helper = { group = "me.lucko", name = "helper", version = "5.6.16-SNAPSHOT" }
helper-sql = { group = "me.lucko", name = "helper-sql", version = "1.3.2" }
helper-redis = { group = "me.lucko", name = "helper-redis", version = "1.2.1" }
helper-profiles = { group = "me.lucko", name = "helper-profiles", version = "1.2.0" }
luckperms = { group = "net.luckperms", name = "api", version = "5.4" }
vault = { group = "com.github.MilkBowl", name = "VaultAPI", version = "1.7" }
essentials = { group = "net.essentialsx", name = "EssentialsX", version = "2.19.0" }
towny = { group = "com.palmergames.bukkit.towny", name = "towny", version = "0.99.0.6" }
itemsadder = { group = "com.github.LoneDev6", name = "api-itemsadder", version = "3.4.1-r4" }
mythicmobs = { group = "io.lumine", name = "Mythic-Dist", version = "5.5.1" }
mythiclib = { group = "io.lumine", name = "MythicLib-dist", version = "1.6-SNAPSHOT" }
mmoitems = { group = "net.Indyuce", name = "MMOItems-API", version = "6.9.4-SNAPSHOT" }
interactivebooks = { group = "net.leonardo_dgs", name = "InteractiveBooks", version = "1.6.5" }
brewery = { group = "com.dre", name = "Brewery", version = "3.1.1" }
miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version = "2.2.3" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version = "2.11.2" }
gemseco = { group = "me.xanium.gemseconomy", name = "api", version = "latest.release" }
gemseconomy = { group = "me.xanium.gemseconomy", name = "api", version = "latest.release" }
protocollib = { group = "com.comphenix.protocol", name = "ProtocolLib", version = "5.0.0" }
connector-core = { group = "de.themoep.connectorplugin", name = "core", version = "1.5-SNAPSHOT" }
connector-bukkit = { group = "de.themoep.connectorplugin", name = "bukkit", version = "1.5-SNAPSHOT" }
nochestplus = { group = "fr.neatmonster", name = "nocheatplus", version = "3.16.1-SNAPSHOT" }
worldguardwrapper = { group = "org.codemc.worldguardwrapper", name = "worldguardwrapper", version = "1.2.0-SNAPSHOT" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version = "7.0.6" }
worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version = "7.2.14" }
citizens = { group = "net.citizensnpcs", name = "citizensapi", version = "2.0.29-SNAPSHOT" }
floodgate = { group = "org.geysermc.floodgate", name = "api", version = "2.2.0-SNAPSHOT" }
chatchat-api = { group = "at.helpch", name = "api", version = "1.0-SNAPSHOT" }
chatchat-plugin = { group = "at.helpch", name = "plugin", version = "1.0-SNAPSHOT" }
betonquest = { group = "org.betonquest", name = "betonquest", version = "2.0.1-SNAPSHOT" }
huskhomes-bukkit = { group = "net.william278.huskhomes", name = "huskhomes-bukkit", version = "4.7" }
husksync-bukkit = { group = "net.william278.husksync", name = "husksync-bukkit", version = "3.6.8" }
papiproxybridge = { group = "net.william278", name = "papiproxybridge", version = "1.2.2" }
adventurelevel = { group = "cc.mewcraft.adventurelevel", name = "api", version = "1.1.0" }

[bundles]

invui = ["invui-core", "invui-invaccess", "invui-invaccess-nms", "invui-extra-kotlin"]
command-paper = ["cloud-paper", "cloud-minecraft-extras"]
command2-paper = ["cloud2-core", "cloud2-paper", "cloud2-minecraft-extras"]
command-velocity = ["cloud-velocity", "cloud-minecraft-extras"]
command2-velocity = ["cloud2-core", "cloud2-velocity", "cloud2-minecraft-extras"]
mccoroutine-bukkit = ["mccoroutine-bukkit-api", "mccoroutine-bukkit-core"]
mccoroutine-velocity = ["mccoroutine-velocity-api", "mccoroutine-velocity-core"]

[plugins]

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
paperdev = { id = "io.papermc.paperweight.userdev", version = "1.7.5" }
pluginyml-paper = { id = "de.eldoria.plugin-yml.paper", version = "0.7.1" }
pluginyml-bukkit = { id = "de.eldoria.plugin-yml.bukkit", version = "0.7.1" } # We should never need it, never
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }